version: '2'

networks:
  async-dev:
    driver: bridge

services:

  async-dev-postgres:
    image: postgres
    networks:
      - async-dev
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
